version: "3.8"
services:
  postgres:
    image: postgres:15.1-alpine3.17
    container_name: postgres_todo
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: /data/

    volumes:
      - ./database:/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U admin -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
  api:
    build: .
    container_name: api_todo
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
        - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/todo_api
      - ./app/alembic:/todo_api/alembic
      - ./app/alembic.ini:/todo_api/alembic.ini